// Use .apex files to store anonymous Apex.
// You can execute anonymous Apex in VS Code by selecting the
//     apex text and running the command:
//     SFDX: Execute Anonymous Apex with Currently Selected Text
// You can also execute the entire file by running the command:
//     SFDX: Execute Anonymous Apex with Editor Contents

System.debug(Calculator.Add(1,2));
System.debug(Calculator.Multiply(2,2));
System.debug(Calculator.Divide(4,2));
System.debug(Calculator.Mod(7,2));